FROM ubuntu:20.04


RUN  apt-get update \
     && apt-get libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libcups2-dev libfreetype6-dev libasound2-dev ccache -y 
     
VOLUME /root/env
WORKDIR /root/env
